name: push develop

on:
  push:
    branches: [dev]

jobs:
  extract_branch:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.step1.outputs.branch }}
    steps:
      - id: step1
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install deps
        run: npm install -g npm@7 && npm ci
      - name: Run build
        env:
          VUE_APP_FATHOM_SITE_ID: xxx
          VUE_APP_GA_ID: xxx
        run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: build_result
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build, extract_branch]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build_result
          path: ./dist

      - name: push ${{ needs.extract_branch.outputs.name }} branch to pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: ureeka-${{ needs.extract_branch.outputs.name }}
          path: ./dist
          pinata-api-key: '${{ secrets.PINATA_API_KEY }}'
          pinata-secret-api-key: '${{ secrets.PINATA_SECRET_API_KEY }}'
          verbose: true
          remove-old: false

  cloudflare_purge_cache:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
